# Generated by Django 5.2.3 on 2025-07-01 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g., BR, US, FR)', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Country code must be 2 uppercase letters', regex='^[A-Z]{2}$')])),
                ('name', models.CharField(help_text='Full country name', max_length=100)),
                ('flag_code', models.CharField(blank=True, help_text='Flag icon code, defaults to country code if empty', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
